import React from 'react';

interface ContentProps {

}

const Content: React.FC<ContentProps> = (props: ContentProps) => {
  return (
    <main>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
      <section>Content</section>
    </main>
  );
}

export default Content;